version: '3.8'
services:
  web:
    image: docker.io/nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network
  db:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_USER: postgresusr
      POSTGRES_PASSWORD: StageP@ss
    volumes:
      - /workspace/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: docker.io/dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: StageP@ss
    ports:
      - "5432:5432"
